*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Aug 22 14:24:00 2020] ***
compiled with version: 7.5.0 on 22 August 2020 04:43:02
os: Linux-5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020
nodename: user-virtual-machine
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/user/Desktop/typeidea-env/typeidea
writing pidfile to uwsgi.pid
detected binary path: /home/user/.virtualenvs/untitle/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/user/Desktop/typeidea-env/typeidea
your processes number limit is 7652
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:8888 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:34737 (port auto-assigned) fd 3
Python version: 3.6.9 (default, Jul 17 2020, 12:50:27)  [GCC 8.4.0]
Python main interpreter initialized at 0x55a6c3dcd3e0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416720 bytes (406 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
Traceback (most recent call last):
  File "typeidea/typeidea/wsgi.py", line 17, in <module>
    application = get_wsgi_application()
  File "/home/user/.virtualenvs/untitle/lib/python3.6/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/user/.virtualenvs/untitle/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/user/.virtualenvs/untitle/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/user/.virtualenvs/untitle/lib/python3.6/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'blog'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 7747)
spawned uWSGI worker 1 (pid: 7749, cores: 2)
spawned uWSGI worker 2 (pid: 7750, cores: 2)
spawned uWSGI worker 3 (pid: 7751, cores: 2)
spawned uWSGI worker 4 (pid: 7752, cores: 2)
spawned uWSGI http 1 (pid: 7757)
